---
name: linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-linting:
    uses: telekom-mms/.github/.github/workflows/golang_linting.yml@4f66e7ff513e18bbec221f7633a1c8164fa5ea2a # main
