---
name: linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-linting:
    uses: telekom-mms/.github/.github/workflows/golang_linting.yml@2139d13acda7a773080f77b3d0479f83c20190ea # main
